/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAvailabilityRouteImport } from './routes/_authenticated/availability'
import { Route as AuthenticatedChecklistRouteImport } from './routes/_authenticated/checklist'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedRosterRouteImport } from './routes/_authenticated/roster'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'
import { Route as AuthenticatedAdminAttendanceRouteImport } from './routes/_authenticated/admin/attendance'
import { Route as AuthenticatedAdminChecklistRouteImport } from './routes/_authenticated/admin/checklist'
import { Route as AuthenticatedAdminEquipmentRouteImport } from './routes/_authenticated/admin/equipment'
import { Route as AuthenticatedAdminMembersRouteImport } from './routes/_authenticated/admin/members'
import { Route as AuthenticatedAdminRosterRouteImport } from './routes/_authenticated/admin/roster'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAvailabilityRoute =
  AuthenticatedAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChecklistRoute = AuthenticatedChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRosterRoute = AuthenticatedRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/admin/analytics',
    path: '/admin/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAttendanceRoute =
  AuthenticatedAdminAttendanceRouteImport.update({
    id: '/admin/attendance',
    path: '/admin/attendance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminChecklistRoute =
  AuthenticatedAdminChecklistRouteImport.update({
    id: '/admin/checklist',
    path: '/admin/checklist',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEquipmentRoute =
  AuthenticatedAdminEquipmentRouteImport.update({
    id: '/admin/equipment',
    path: '/admin/equipment',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMembersRoute =
  AuthenticatedAdminMembersRouteImport.update({
    id: '/admin/members',
    path: '/admin/members',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRosterRoute =
  AuthenticatedAdminRosterRouteImport.update({
    id: '/admin/roster',
    path: '/admin/roster',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/availability': typeof AuthenticatedAvailabilityRoute
  '/checklist': typeof AuthenticatedChecklistRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/roster': typeof AuthenticatedRosterRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/admin/checklist': typeof AuthenticatedAdminChecklistRoute
  '/admin/equipment': typeof AuthenticatedAdminEquipmentRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/roster': typeof AuthenticatedAdminRosterRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/availability': typeof AuthenticatedAvailabilityRoute
  '/checklist': typeof AuthenticatedChecklistRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/roster': typeof AuthenticatedRosterRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/admin/checklist': typeof AuthenticatedAdminChecklistRoute
  '/admin/equipment': typeof AuthenticatedAdminEquipmentRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/roster': typeof AuthenticatedAdminRosterRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/availability': typeof AuthenticatedAvailabilityRoute
  '/_authenticated/checklist': typeof AuthenticatedChecklistRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/roster': typeof AuthenticatedRosterRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/_authenticated/admin/checklist': typeof AuthenticatedAdminChecklistRoute
  '/_authenticated/admin/equipment': typeof AuthenticatedAdminEquipmentRoute
  '/_authenticated/admin/members': typeof AuthenticatedAdminMembersRoute
  '/_authenticated/admin/roster': typeof AuthenticatedAdminRosterRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/availability'
    | '/checklist'
    | '/dashboard'
    | '/messages'
    | '/roster'
    | '/settings'
    | '/admin/analytics'
    | '/admin/attendance'
    | '/admin/checklist'
    | '/admin/equipment'
    | '/admin/members'
    | '/admin/roster'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/availability'
    | '/checklist'
    | '/dashboard'
    | '/messages'
    | '/roster'
    | '/settings'
    | '/admin/analytics'
    | '/admin/attendance'
    | '/admin/checklist'
    | '/admin/equipment'
    | '/admin/members'
    | '/admin/roster'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/availability'
    | '/_authenticated/checklist'
    | '/_authenticated/dashboard'
    | '/_authenticated/messages'
    | '/_authenticated/roster'
    | '/_authenticated/settings'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/attendance'
    | '/_authenticated/admin/checklist'
    | '/_authenticated/admin/equipment'
    | '/_authenticated/admin/members'
    | '/_authenticated/admin/roster'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/availability': {
      id: '/_authenticated/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AuthenticatedAvailabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checklist': {
      id: '/_authenticated/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof AuthenticatedChecklistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roster': {
      id: '/_authenticated/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof AuthenticatedRosterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/attendance': {
      id: '/_authenticated/admin/attendance'
      path: '/admin/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AuthenticatedAdminAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/checklist': {
      id: '/_authenticated/admin/checklist'
      path: '/admin/checklist'
      fullPath: '/admin/checklist'
      preLoaderRoute: typeof AuthenticatedAdminChecklistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/equipment': {
      id: '/_authenticated/admin/equipment'
      path: '/admin/equipment'
      fullPath: '/admin/equipment'
      preLoaderRoute: typeof AuthenticatedAdminEquipmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/members': {
      id: '/_authenticated/admin/members'
      path: '/admin/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AuthenticatedAdminMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/roster': {
      id: '/_authenticated/admin/roster'
      path: '/admin/roster'
      fullPath: '/admin/roster'
      preLoaderRoute: typeof AuthenticatedAdminRosterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAvailabilityRoute: typeof AuthenticatedAvailabilityRoute
  AuthenticatedChecklistRoute: typeof AuthenticatedChecklistRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedRosterRoute: typeof AuthenticatedRosterRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminAttendanceRoute: typeof AuthenticatedAdminAttendanceRoute
  AuthenticatedAdminChecklistRoute: typeof AuthenticatedAdminChecklistRoute
  AuthenticatedAdminEquipmentRoute: typeof AuthenticatedAdminEquipmentRoute
  AuthenticatedAdminMembersRoute: typeof AuthenticatedAdminMembersRoute
  AuthenticatedAdminRosterRoute: typeof AuthenticatedAdminRosterRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAvailabilityRoute: AuthenticatedAvailabilityRoute,
  AuthenticatedChecklistRoute: AuthenticatedChecklistRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedRosterRoute: AuthenticatedRosterRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminAttendanceRoute: AuthenticatedAdminAttendanceRoute,
  AuthenticatedAdminChecklistRoute: AuthenticatedAdminChecklistRoute,
  AuthenticatedAdminEquipmentRoute: AuthenticatedAdminEquipmentRoute,
  AuthenticatedAdminMembersRoute: AuthenticatedAdminMembersRoute,
  AuthenticatedAdminRosterRoute: AuthenticatedAdminRosterRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
